---
- name: Launch EC2 instances using loop with Ansible Vault
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    region: ap-south-1
    key_name: aws-key
    instance_type: t2.micro
    security_group: default
    instances:
      - { image: "ami-0e35ddab05955cf57", name: "ubuntu-node-1" }     # Ubuntu 22.04
      - { image: "ami-0e35ddab05955cf57", name: "ubuntu-node-2" }     # Ubuntu 22.04
      - { image: "ami-0af9569868786b23a", name: "amazonlinux-node-1" } # Amazon Linux 2023

  tasks:
    - name: Launch EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        region: "{{ region }}"
        security_group: "{{ security_group }}"
        image_id: "{{ item.image }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        network:
          assign_public_ip: true
        wait: true
        tags:
          Name: "{{ item.name }}"
          environment: dev
      loop: "{{ instances }}"

